# Generated by Django 5.1.6 on 2025-02-18 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('current_page', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('reading', 'Reading'), ('completed', 'Completed'), ('plan_to_read', 'Plan to Read')], default='plan_to_read', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_app', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
